name: Generate a build and push to v4

on:
  push:
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install all dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Push build to v4
        uses: s0/git-publish-subdir-action@develop
        with:
          folder: public
          branch: v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
