name: Generate a build and push to another branch

on:
  push:
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install all dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Debug: List current directory
        run: ls -la

      - name: Debug: List 'public' directory (if exists)
        run: ls -la public || echo "Public folder not found"

      - name: Push build to v4
        run: |
          git config --global user.email "me@pierrelouis.net"
          git config --global user.name "Pierre-Louis"
          git checkout v4
          rm -rf *
          cp -r public/* . || echo "Public folder is missing, nothing to copy."
          git add .
          git commit -m "Build: (${GITHUB_SHA}) ${GITHUB_REF_NAME}"
          git push origin v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
